create database pw3_study;

use pw3_study;

CREATE TABLE TBL_DISCIPLINA(
    ID_DISCIPLINA BIGINT primary key identity ,
    TX_NOME VARCHAR(60) NOT NULL
);



CREATE TABLE TBL_MONITOR(
	ID_MONITOR BIGINT PRIMARY KEY IDENTITY,
	TX_NOME VARCHAR(60) NOT NULL,
	TX_FOTO VARCHAR(255) NOT NULL,
	TX_WHATSAPP VARCHAR(11) NOT NULL,
	TX_EMAIL VARCHAR(40) NOT NULL,
	TX_CONTEUDO VARCHAR(1000) NOT NULL,
	ID_DISCIPLINA BIGINT NOT NULL,
	FOREIGN KEY (ID_DISCIPLINA) REFERENCES TBL_DISCIPLINA (ID_DISCIPLINA)
);

select * from TBL_MONITOR
CREATE TABLE TBL_DISPONIBILIDADE(
    ID_DISPONIBILIDADE BIGINT  PRIMARY KEY IDENTITY,
    TX_DIA_SEMANA VARCHAR(30) NOT NULL,
    DT_DAS DATETIME NOT NULL,
    DT_ATE DATETIME NOT NULL,
);

CREATE TABLE TBL_REL_MONITOR_DISPONIBILIDADE(
	ID_MONITOR BIGINT NOT NULL,
	ID_DISPONIBILIDADE BIGINT NOT NULL,
	FOREIGN KEY (ID_MONITOR) REFERENCES TBL_MONITOR (ID_MONITOR),
	FOREIGN KEY (ID_DISPONIBILIDADE) REFERENCES TBL_DISPONIBILIDADE (ID_DISPONIBILIDADE)
);

CREATE TABLE TBL_CONEXAO(
	ID_CONEXAO BIGINT NOT NULL,
	DT_CRIACAO DATETIME NOT NULL,
	ID_MONITOR BIGINT NOT NULL,
	FOREIGN KEY (ID_MONITOR) REFERENCES TBL_MONITOR (ID_MONITOR)
);


INSERT INTO TBL_DISCIPLINA (TX_NOME) VALUES ('Matemática');
INSERT INTO TBL_DISCIPLINA (TX_NOME) VALUES ('Português');
INSERT INTO TBL_DISCIPLINA (TX_NOME) VALUES ('História');
INSERT INTO TBL_DISCIPLINA (TX_NOME) VALUES ('Geografia');
INSERT INTO TBL_DISCIPLINA (TX_NOME) VALUES ('Química');
INSERT INTO TBL_DISCIPLINA (TX_NOME) VALUES ('Física');
INSERT INTO TBL_DISCIPLINA (TX_NOME) VALUES ('Biologia');
INSERT INTO TBL_DISCIPLINA (TX_NOME) VALUES ('Educação Física');
INSERT INTO TBL_DISCIPLINA (TX_NOME) VALUES ('Arte');
INSERT INTO TBL_DISCIPLINA (TX_NOME) VALUES ('Inglês');

INSERT INTO TBL_MONITOR (TX_NOME, TX_FOTO, TX_WHATSAPP, TX_EMAIL, TX_CONTEUDO, ID_DISCIPLINA) 
VALUES ('João Silva', 'foto_joao.jpg', '11987654321', 'joao.silva@example.com', 'Aulas de Matemática e apoio individual.', 1);

INSERT INTO TBL_MONITOR (TX_NOME, TX_FOTO, TX_WHATSAPP, TX_EMAIL, TX_CONTEUDO, ID_DISCIPLINA) 
VALUES ('Maria Oliveira', 'foto_maria.jpg', '11987654322', 'maria.oliveira@example.com', 'Tutoria de Português e revisão de textos.', 2);

INSERT INTO TBL_MONITOR (TX_NOME, TX_FOTO, TX_WHATSAPP, TX_EMAIL, TX_CONTEUDO, ID_DISCIPLINA) 
VALUES ('Carlos Pereira', 'foto_carlos.jpg', '11987654323', 'carlos.pereira@example.com', 'Aulas de História e estudos dirigidos.', 3);

INSERT INTO TBL_MONITOR (TX_NOME, TX_FOTO, TX_WHATSAPP, TX_EMAIL, TX_CONTEUDO, ID_DISCIPLINA) 
VALUES ('Ana Costa', 'foto_ana.jpg', '11987654324', 'ana.costa@example.com', 'Acompanhamento em Geografia e preparação para provas.', 4);

INSERT INTO TBL_MONITOR (TX_NOME, TX_FOTO, TX_WHATSAPP, TX_EMAIL, TX_CONTEUDO, ID_DISCIPLINA) 
VALUES ('Pedro Lima', 'foto_pedro.jpg', '11987654325', 'pedro.lima@example.com', 'Aulas de Química e experimentos laboratoriais.', 5);

INSERT INTO TBL_MONITOR (TX_NOME, TX_FOTO, TX_WHATSAPP, TX_EMAIL, TX_CONTEUDO, ID_DISCIPLINA) 
VALUES ('Juliana Santos', 'foto_juliana.jpg', '11987654326', 'juliana.santos@example.com', 'Revisão e exercícios de Física.', 6);

INSERT INTO TBL_MONITOR (TX_NOME, TX_FOTO, TX_WHATSAPP, TX_EMAIL, TX_CONTEUDO, ID_DISCIPLINA) 
VALUES ('Roberto Almeida', 'foto_roberto.jpg', '11987654327', 'roberto.almeida@example.com', 'Aulas de Biologia e práticas laboratoriais.', 7);

INSERT INTO TBL_MONITOR (TX_NOME, TX_FOTO, TX_WHATSAPP, TX_EMAIL, TX_CONTEUDO, ID_DISCIPLINA) 
VALUES ('Clara Martins', 'foto_clara.jpg', '11987654328', 'clara.martins@example.com', 'Educação Física e preparação para competições.', 8);

INSERT INTO TBL_MONITOR (TX_NOME, TX_FOTO, TX_WHATSAPP, TX_EMAIL, TX_CONTEUDO, ID_DISCIPLINA) 
VALUES ('Lucas Pereira', 'foto_lucas.jpg', '11987654329', 'lucas.pereira@example.com', 'Aulas de Arte e desenvolvimento criativo.', 9);

INSERT INTO TBL_MONITOR (TX_NOME, TX_FOTO, TX_WHATSAPP, TX_EMAIL, TX_CONTEUDO, ID_DISCIPLINA) 
VALUES ('Fernanda Lima', 'foto_fernanda.jpg', '11987654330', 'fernanda.lima@example.com', 'Aulas de Inglês e conversação prática.', 10);

INSERT INTO TBL_DISPONIBILIDADE (TX_DIA_SEMANA, DT_DAS, DT_ATE) 
VALUES ('Segunda-feira', '2024-09-16 08:00:00', '2024-09-16 12:00:00');

INSERT INTO TBL_DISPONIBILIDADE (TX_DIA_SEMANA, DT_DAS, DT_ATE) 
VALUES ('Terça-feira', '2024-09-17 13:00:00', '2024-09-17 17:00:00');

INSERT INTO TBL_DISPONIBILIDADE (TX_DIA_SEMANA, DT_DAS, DT_ATE) 
VALUES ('Quarta-feira', '2024-09-18 09:00:00', '2024-09-18 11:00:00');

INSERT INTO TBL_DISPONIBILIDADE (TX_DIA_SEMANA, DT_DAS, DT_ATE) 
VALUES ('Quinta-feira', '2024-09-19 14:00:00', '2024-09-19 18:00:00');

INSERT INTO TBL_DISPONIBILIDADE (TX_DIA_SEMANA, DT_DAS, DT_ATE) 
VALUES ('Sexta-feira', '2024-09-20 10:00:00', '2024-09-20 15:00:00');

INSERT INTO TBL_DISPONIBILIDADE (TX_DIA_SEMANA, DT_DAS, DT_ATE) 
VALUES ('Sábado', '2024-09-21 09:00:00', '2024-09-21 12:00:00');

INSERT INTO TBL_DISPONIBILIDADE (TX_DIA_SEMANA, DT_DAS, DT_ATE) 
VALUES ('Domingo', '2024-09-22 10:00:00', '2024-09-22 14:00:00');

INSERT INTO TBL_DISPONIBILIDADE (TX_DIA_SEMANA, DT_DAS, DT_ATE) 
VALUES ('Segunda-feira', '2024-09-23 13:00:00', '2024-09-23 17:00:00');

INSERT INTO TBL_DISPONIBILIDADE (TX_DIA_SEMANA, DT_DAS, DT_ATE) 
VALUES ('Quarta-feira', '2024-09-25 08:00:00', '2024-09-25 12:00:00');

INSERT INTO TBL_DISPONIBILIDADE (TX_DIA_SEMANA, DT_DAS, DT_ATE) 
VALUES ('Sexta-feira', '2024-09-27 14:00:00', '2024-09-27 18:00:00');

INSERT INTO TBL_REL_MONITOR_DISPONIBILIDADE (ID_MONITOR, ID_DISPONIBILIDADE) 
VALUES (1, 1);

INSERT INTO TBL_REL_MONITOR_DISPONIBILIDADE (ID_MONITOR, ID_DISPONIBILIDADE) 
VALUES (1, 2);

INSERT INTO TBL_REL_MONITOR_DISPONIBILIDADE (ID_MONITOR, ID_DISPONIBILIDADE) 
VALUES (2, 3);

INSERT INTO TBL_REL_MONITOR_DISPONIBILIDADE (ID_MONITOR, ID_DISPONIBILIDADE) 
VALUES (2, 4);

INSERT INTO TBL_REL_MONITOR_DISPONIBILIDADE (ID_MONITOR, ID_DISPONIBILIDADE) 
VALUES (3, 5);

INSERT INTO TBL_REL_MONITOR_DISPONIBILIDADE (ID_MONITOR, ID_DISPONIBILIDADE) 
VALUES (3, 6);

INSERT INTO TBL_REL_MONITOR_DISPONIBILIDADE (ID_MONITOR, ID_DISPONIBILIDADE) 
VALUES (4, 7);

INSERT INTO TBL_REL_MONITOR_DISPONIBILIDADE (ID_MONITOR, ID_DISPONIBILIDADE) 
VALUES (4, 8);

INSERT INTO TBL_REL_MONITOR_DISPONIBILIDADE (ID_MONITOR, ID_DISPONIBILIDADE) 
VALUES (5, 9);

INSERT INTO TBL_REL_MONITOR_DISPONIBILIDADE (ID_MONITOR, ID_DISPONIBILIDADE) 
VALUES (5, 10);

INSERT INTO TBL_CONEXAO (ID_CONEXAO, DT_CRIACAO, ID_MONITOR) 
VALUES (1, '2024-09-16 08:00:00', 1);

